import { Plus, Filter, Download } from "lucide-react";

export default function CRMPage() {
  const leads = [
    { id: 1, name: "Acme Corp", email: "contact@acme.co", source: "Website", status: "NEW", date: "Today" },
    { id: 2, name: "Global Tech", email: "info@gtech.io", source: "WhatsApp", status: "CONTACTED", date: "Yesterday" },
    { id: 3, name: "Alpha Agency", email: "hello@alpha.agency", source: "Instagram", status: "QUALIFIED", date: "3 days ago" },
    { id: 4, name: "Design Studio", email: "hi@design.co", source: "Website", status: "PROPOSAL", date: "1 week ago" },
    { id: 5, name: "Local Bakery", email: "orders@bakery.local", source: "WhatsApp", status: "WON", date: "2 weeks ago" },
  ];

  const statusColors: Record<string, string> = {
    NEW: "bg-blue-100 text-blue-800",
    CONTACTED: "bg-yellow-100 text-yellow-800",
    QUALIFIED: "bg-purple-100 text-purple-800",
    PROPOSAL: "bg-orange-100 text-orange-800",
    WON: "bg-emerald-100 text-emerald-800",
  };

  return (
    <div className="space-y-6">
      <div className="flex sm:items-center justify-between flex-col sm:flex-row gap-4">
        <div>
          <h1 className="text-2xl font-bold text-neutral-900">CRM & Leads</h1>
          <p className="mt-1 text-sm text-neutral-500">
            Manage your incoming leads generated by your AI agents.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button className="flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-neutral-700 shadow-sm ring-1 ring-inset ring-neutral-300 hover:bg-neutral-50 transition">
            <Filter className="h-4 w-4" /> Filter
          </button>
          <button className="flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-semibold text-neutral-700 shadow-sm ring-1 ring-inset ring-neutral-300 hover:bg-neutral-50 transition">
            <Download className="h-4 w-4" /> Export
          </button>
          <button className="flex items-center gap-2 rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-700 transition">
            <Plus className="h-4 w-4" /> Add Lead
          </button>
        </div>
      </div>

      <div className="overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-neutral-200">
            <thead className="bg-neutral-50">
              <tr>
                <th scope="col" className="py-3.5 pl-6 pr-3 text-left text-sm font-semibold text-neutral-900">Lead Name</th>
                <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-neutral-900">Source</th>
                <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-neutral-900">Status</th>
                <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-neutral-900">Date Added</th>
                <th scope="col" className="relative py-3.5 pl-3 pr-6">
                  <span className="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-200 bg-white">
              {leads.map((lead) => (
                <tr key={lead.id} className="hover:bg-neutral-50 transition-colors">
                  <td className="whitespace-nowrap py-4 pl-6 pr-3 text-sm">
                    <div className="font-medium text-neutral-900">{lead.name}</div>
                    <div className="text-neutral-500">{lead.email}</div>
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm text-neutral-500">
                    <span className="inline-flex items-center rounded-md px-2 py-1 text-xs font-medium border border-neutral-200 bg-neutral-50 text-neutral-600">
                      {lead.source}
                    </span>
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm">
                    <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${statusColors[lead.status]}`}>
                      {lead.status}
                    </span>
                  </td>
                  <td className="whitespace-nowrap px-3 py-4 text-sm text-neutral-500">{lead.date}</td>
                  <td className="relative whitespace-nowrap py-4 pl-3 pr-6 text-right text-sm font-medium">
                    <a href="#" className="text-blue-600 hover:text-blue-900 transition">
                      View details
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
